version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Disable version update PRs; only security updates will be opened.
    open-pull-requests-limit: 0
