version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # don't send notifications for demo apps
      - directory: "demos"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0