name: Tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  unit:
    strategy:
      matrix:
        node_version: [20, 22, 24]
    runs-on: ubuntu-latest
    name: Unit Tests on Node v${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - run: yarn install --frozen-lockfile
      - run: yarn run test:coverage
